global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - alerts.yaml

scrape_configs:
  - job_name: api-reliability-monitor
    static_configs:
      - targets:
          - app:5001
    metrics_path: /metrics
