apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-reliability-monitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gatraj/api-reliability-monitor
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: api-reliability-monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
